# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: <p style="font-size:24px"> About
    url: '#about'
    weight: 10
  - name: <p style="font-size:24px"> Publications
    url: 'publication/'
    weight: 30
  - name: <p style="font-size:24px"> Experience & Skills
    url: 'exp'
    weight: 20
  - name: <p style="font-size:24px"> Book Me
    url: "booking"
    weight: 45
  #  - name: Talks
  #    url: 'talks/'
  #    weight: 30
  - name: <p style="font-size:24px"> CV
    url: "cv"
    weight: 40
    # - name: <p style="font-size:24px"> Fitness
    #   url: "https://pro.everfit.io/tawaun-lucas"
    #   weight: 100

#  - name: File Drawer
#    url: filedrawer/
#    weight: 30 # keep as draft before committing
#  - name: Contact
#    url: '#contact'
#    weight: 70
